version: '3'

services:
  cs2-server:
    env_file:
      - .env
    build:
      context: .
      args:
        - STEAMUSER=${STEAMUSER}
        - STEAMPASS=${STEAMPASS}
        - SERVERPATH=${SERVERPATH}
        - CFGPATH=${CFGPATH}
        
      dockerfile: Dockerfile
    ports:
      - "27015:27015"
      - "27016:27016"
    volumes:
      - cs2-server-data:/home/steam/server
      - steamcd_login:/home/steam/Steam
      
volumes:
  cs2-server-data:
  steamcd_login: